// Generated by CoffeeScript 1.9.1
var config, data, product_id, req, script, scriptSrc;

script = document.getElementById('we-widget-script');

scriptSrc = script.getAttribute('src');

scriptSrc = scriptSrc.substring(0, scriptSrc.lastIndexOf('/'));

product_id = window.wide_eyes_product_id;

config = window.wide_eyes_config;

data = {
  ProductId: product_id,
  MinNumResults: config.numberOfElements + 1 || 5
};

req = new XMLHttpRequest();

req.addEventListener('readystatechange', function() {
  var html, iframe, response, widget;
  if (req.readyState === 4 && req.status === 200) {
    response = JSON.parse(req.responseText);
    response.result_both.splice(0, 2);
    iframe = document.createElement('iframe');
    iframe.setAttribute('width', '100%');
    iframe.setAttribute('id', 'we-iframe');
    iframe.setAttribute('seamless', true);
    iframe.setAttribute('frameborder', 'no');
    iframe.setAttribute('scrolling', 'no');
    iframe.setAttribute('onload', 'iFrameResize({checkOrigin: false}, "#we-iframe")');
    widget = document.getElementById('widget');
    widget.appendChild(iframe);
    if (config.mode === 'debug') {
      response = JSON.stringify(response);
      config = JSON.stringify(config);
      html = '<!DOCTYPE html> <html> <head> <script> var products = ' + response + '; var config = ' + config + '; var product_id = "' + product_id + '"; </script> <link rel="stylesheet" href="' + scriptSrc + '/css/main.css"> <base target="_blank"/> </head> <body> <section id="widget"></section> <script src="' + scriptSrc + '/vendor/requirejs/require.js"></script> <script src="' + scriptSrc + '/vendor/iframe-resizer/src/iframeResizer.contentWindow.js"></script> <script src="' + scriptSrc + '/main.js"></script> </body> </html>';
    } else if (config.mode === 'production' || !config.mode) {
      response = JSON.stringify(response);
      config = JSON.stringify(config);
      html = '<!DOCTYPE html> <html> <head> <script> var products = ' + response + '; var config = ' + config + '; var product_id = "' + product_id + '"; </script> <link rel="stylesheet" href="' + scriptSrc + '/main.min.css"> <base target="_blank"/> </head> <body> <section id="widget"></section> <script src="' + scriptSrc + '/main_internal.min.js"></script> </body> </html>';
    }
    iframe.contentWindow.document.open();
    iframe.contentWindow.document.write(html);
    return iframe.contentWindow.document.close();
  }
});

req.open('POST', 'http://api.wide-eyes.it/v1/SearchById', true);

req.setRequestHeader('apikey', config.apikey);

req.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');

req.send(JSON.stringify(data));
