// Generated by CoffeeScript 1.9.1
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(function(require) {
  var Backbone, WeSaas, _;
  _ = require('underscore');
  Backbone = require('backbone');
  return WeSaas = (function(superClass) {
    extend(WeSaas, superClass);

    function WeSaas() {
      return WeSaas.__super__.constructor.apply(this, arguments);
    }

    WeSaas.prototype.urlRoot = function() {
      return 'http://api.wide-eyes.it/v1/SearchById';
    };

    WeSaas.prototype.initialize = function() {
      return this.listenTo(this, 'sync', this._onSync);
    };

    WeSaas.prototype.save = function() {
      this.set(this._submodelsToJSON());
      return WeSaas.__super__.save.call(this, {}, {
        headers: {
          'Authorization': 'api_key ' + window.bearer_token
        }
      });
    };

    WeSaas.prototype.hasUnsavedChanges = function() {
      return !_.isEqual(this.toJSON(), this._lastSavedData);
    };

    WeSaas.prototype._onSync = function() {
      return this._lastSavedData = this.toJSON();
    };

    return WeSaas;

  })(Backbone.Model);
});
