language: node_js

node_js:
  - '0.11'

notifications:
  email:
    recipients:
      - gerard@wide-eyes.it
    on_failure: change

before_script:
  - ./start_sc_server.sh
  - sleep 10

script:
  - npm run test

branches:
  only:
    - master

env:
  global:
  - secure: RDgpGzj3v1o4waIcbmrK2LtGKQhI/mg8RseLVhymnk1C1RRxfDMyAPPtC/IHKfPsAm5yAEUsb4Q43cIkQchv9jRBmmYFglmavLSpmf/KKRgHVKZzYOyG+otTzQrpfEPGSIe9rsMmK2cmUHbxgFeFKSwIy6RYu7FTHlFx/WBxcBZKo822Af47uxNUWWqBcg7+L+TQs4X6pjnrwezDr/0bDfZ4cYFBFY1IRp4xEU9LTYrM+/Kmzfm4IQkLmNt/wiyYPdfRu7OY8YdIoEplKuAfDJafzC+9Lf/brJyYHGWusefzg9uZropF7ZKrWY6cm+IiW3NTBMIga+4nkE8hueIeqSIJ6f0rCbM9VHx0aV2luZcMf9IobSfDFZl3/47UI44IgUWykIjJIXn2ZRYUjVPMdf8JxZnswvEkvk+JbGmK1d1c107w51Z83r4Yk/dcqtavxX4/h69sscmU4SHIlTiesjedGYPTCIzair5UcG7jPTrYH46ASY3uFYYyaY7CiMetWseeCXeR1cH1Motl4TlvWm6ce3lw/kTZ/HJOv0UZj8odXqbsnoxSK70J9P9R24OCkGYZbJaLdtowlNgt/ntIj7RhvNrO3mFbMqGP5qILUpgoipD/NbgZQ/bq/FfrpIfUB8Oxyv7c8Gg/uqa2J4G7eaGF3hM3wrNCiL5l9Ho1f88=
  - secure: d2ecwhAUgjRoq5aMmrftxlrQD9Q+Z5lEUe7VM8E4Cvtua8eEvgwvmM+eCY4MteaUF9Oju+g1G1YbbFgLkvD8BDjFyOsX7wGkS7FxMOZE+auj8yvDOzB2k6VrIpOQrGGq+L1q1RPUIkd+PA4uYkKD+VJcT5Q7BQndzDXeEwwlMp/KK3VNDLnWkt9ojN44WtRJPiaTFGvoQ/lYEutpKubMGZj1Ac1VwWCEau4gnh8bE2q9Dpic/1eEWYFtbNsmiXLgPRkgMEUdcthzB2Ucd2wY/1O6Y9MwOwLecbVr3Wdh804l8TQQMFeMT0QXzWlN63La8xOyBlpc3KptXGumzqHmWWNQljjiloUpZDD3AWmso+BnvD1Y5aJ2CsaU0OBYnHHSPRcL25KXVdQ1LZYlLKjdoYAcQcy+0CQE7sX6kiKZil/GkXNTF4LTPo+7TRNgbqqWMGB/Fx6rSzREZ6ttplEB1gFgJdkIIiC6JdWeRiw3li69TorKGIf9373rzih1uO3EdtTvQetdHkO70VJ0KpNJLRm169FfGUoMbXsIH0Xo6wDuPnhh0l39EsZ73TDagAy0zQMOMqg6mOgZAerNUwzlaQqKIqoejmAjTFex/KnFPlOYBIBWvOpt8O5fkmCGVXVlLz+muOYfjMYDVwHt5guStiRFHeK3OCZtoFrrX64n1kg=

addons:
  sauce_connect: true